config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :events, only: %i[index new create show edit update]
  resource :dashboard, only: :show
  resources :notifications, only: %i[index] do
    patch 'read', on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  before_validation :set_category
  CATEGORIES = %w[Sport Culture Voyage Autres]

  has_one_attached :document
  has_many :notifications, dependent: :destroy
  belongs_to :user
  validates :title, :venue, :starts_at, :address, :category, presence: true, if: -> { status == "after_ocr" }
  validates :category, inclusion: { in: CATEGORIES }, if: -> { status == "after_ocr" }

  private

  def set_category
    return if category.present?

    self.category = "Autres"
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :event
  has_one :user, through: :event
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, dependent: :destroy
  has_many :notifications, through: :events
  has_one_attached :avatar
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone, presence: true, uniqueness: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name phone avatar])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name phone avatar])
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @date = DateTime.now
    @events = current_user.events.where("starts_at >= ? ", @date).order(:starts_at)
    @events = @events.first(4)
    @event = @events.first
    @notification = current_user.notifications.where(read: false).first
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :find_event, only: %i[show edit update]
  before_action :user

  def index
    @events = current_user.events.order(:starts_at)

    if params[:category].present?
      @events = @events.where(category: params[:category])
    end

    if params["date"]
      @date = params["date"].to_date
    else
      @date = Date.today
    end

    @year = Date.today.year

    @events = @events.where(starts_at: @date.beginning_of_month..@date.end_of_month)

    # event.starts_at - Time.current > 0

    @next_event = @events.where(starts_at: (Time.current - 1.day)..).first
  end

  def show

   if @event.user != current_user
    flash[:alert] = "Vous ne pouvez pas acceder à cette page"
    redirect_to root_path
   end

    category_marker_class_mapping = {
      "Sport"   => "fa-volleyball sport-color",
      "Culture" => "fa-book culture-color",
      "Voyage"  => "fa-plane-departure voyage-color",
      "Autres"  => "fa-star-of-life autres-color"
    }

    @marker = {
      lat: @event.latitude,
      lng: @event.longitude,
      class_name: "fa-solid fa-2x #{category_marker_class_mapping[@event.category]}"
    }
  end

  def new
    @user = current_user
    @event = Event.new
  end

  def create
    @user = current_user
    @event = Event.new(event_params)
    @event.user = @user
    if @event.save
      ExtractEventInfos.new(@event).call
      redirect_to edit_event_path(@event)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @event.update(event_params)
    redirect_to event_path(@event)
  end


  private

  def event_params
    params.require(:event).permit(:title, :venue, :starts_at,
      :address, :latitude, :longitude, :category,
      :identity_card,:driver_card, :passport, :document
    )
  end

  def find_event
    @event = Event.find(params[:id])
  end

  def user
    @user = current_user
  end

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  def index
    @notifications = Notification.all.order(:created_at)
    @notifications.each do |notif|
      notif.read = true
      notif.save
    end
  end


  def read
    @notification = Notification.find(params[:id])
    @notification.read = true
    @notification.save
    redirect_to dashboard_path
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    if user_signed_in?
      redirect_to dashboard_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # def embedded_svg(path)
  #   File.open("app/assets/images/componentssvg/#{path}", "rb") do |file|
  #     raw file.read
  #   end
  # end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/dashboards/show.html.erb
<div data-controller="notification-subscription"  data-notification-subscription-target="notifications" data-notification-subscription-current-user-id-value="<%= current_user.id%>" > <%# %>
  <% if @notification %>
      <%= link_to notifications_path do %>
        <%= render "notifications/notification", notification: @notification %>
      <% end %>
  <% end %>
</div>

<div class="container1 margin-bottom-80">


  <% nb = @events.length %>
  <% if nb == 0 %>
    <h2 class='info-title'>Aucun évènement</h2>
  <% else %>
    <h2 class='info-title'>Prochain évènement</h2>
      <div class="ticket-cont" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
        <embed src="<%= cl_image_path @events.first.document.key, format: "png", gravity: "north_east", quality:"auto:best",width: 150, height: 150, x: 142, y: 457, crop: "crop" %>" width="100" height="100">
        <div class="card-event-info first-cont">
          <h3><%= @events.first.title %></h3>
          <p><%= @events.first.venue %> <br> <%= l((@events.first.starts_at), format: ("%A %e %B %Y à %k:%M")).capitalize %></p>
        </div>
      </div>
    <% if nb == 1 %>
      <h2 class='info-title'>Aucun autre évènement</h2>
    <% else %>
      <h2 class='info-title'>Evènements suivants</h2>
      <% for i in 1..(nb - 1) %>
        <%= link_to event_path(@events[i]), class: "name" do %>
          <div class="ticket-cont">
            <embed src="<%= cl_image_path @events[i].document.key, format: "png", gravity: "north_east", quality:"auto:best",width: 150, height: 150, x: 142, y: 457, crop: "crop" %>" width="100" height="100">
            <div class="card-event-info">
              <h3><%= @events[i].title %></h3>
              <p><%= @events[i].venue %> <br> <%= l((@events[i].starts_at), format: ("%A %e %B %Y à %k:%M")).capitalize %></p>
              <p></p>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  <% end %>



  <!-- Modal -->
  <% if nb > 0 %>
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
      <div class="modal-dialog modal-fullscreen-sm-down">
        <div class="modal-content">
          <div class="modal-body mod-card-cont">
          <div class="modal-header">
            <h2 class="modal-title me-5 mt-3" id="staticBackdropLabel">Prochain évènement</h2>
            <button type="button" class="btn-close mt-3" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
            <div class='mod-card-code'>
              <embed src="<%= cl_image_path @event.document.key, format: "png", gravity: "north_east", quality:"auto:best",width: 150, height: 150, x: 142, y: 457, crop: "crop" %>" width="200" height="200" class="modal-img">
            </div>
            <div class='mod-card-info'>
              <h3><%= @event.title %></h3>
              <p><%= @event.venue %> <br> <%= l((@event.starts_at), format: ("%A %e %B %Y à %k:%M")).capitalize %></p>
            </div>
            <%= link_to "Voir l'évenement", event_path(@event), class:'btn-sign-in' %>
          </div>
        </div>
      </div>
    </div>
  <% end %>




</div>

app/views/events/edit.html.erb
<div class="container mb-5 p-5">
    <%= link_to :back, class:'btn-back' do %>
    <i class="fa-solid fa-angle-left"></i>
  <% end %>
    <div class="form-container mt-1">
      <h3>Informations</h3>
      <br>
      <%= simple_form_for(@event) do |f| %>
        <%= f.input :title, label: "Titre", required: true, placeholder: "Ex: Le Lac des Cygnes" %>
        <%= f.input :venue, label: "Lieu", required: true, placeholder: "Ex: Opéra Garnier" %>
        <%= f.input :address, label: "Adresse", required: true, placeholder: "Ex: Place de l'Opéra 75009 Paris" %>
        <%= f.input :starts_at, label: "Date", required: true, html5: true %>
        <div class="div h-200">
          <%= f.input :category, label: "Catégorie", collection: Event::CATEGORIES %>
        </div>
        <%= f.submit 'Valider', class: 'btn-add-event'%>
      <% end %>
    </div>
</div>

app/views/events/index.html.erb
<div class="container2 margin-bottom-80">
  <div class='sticky-head-events'>
    <div class='d-flex justify-content-around align-items-center mb-4'>
      <%= link_to events_path(date: @date - 1.month, category: params[:category]) do  %>
        <h5> <small> <i class="fa-solid fa-arrow-left-long"></i> </small> <%= l((@date - 1.month), format: "%b").capitalize %></h5>
    <% end %>
    <h3><strong><%= l(@date, format: "%^B") %></strong> <small><%= if @date.year != @year then l(@date, format: "%y") end %></small></h3>
    <%= link_to events_path(date: @date + 1.month, category: params[:category]) do %>
      <h5><%= l((@date + 1.month), format: "%b").capitalize %> <small> <i class="fa-solid fa-arrow-right"></i> </small></h5>
    <% end  %>
  </div>



    <div class='d-flex justify-content-around mb-3' data-controller="category" >
      <div data-action="click->category#choose_sport">
        <%= link_to events_path(date: @date, category: (params[:category] == "Sport" ? nil : "Sport")) do %>
          <i class="align-middle fa-solid <%= if params[:category] == "Sport" then 'fa-2x' else 'fa-xl' end %> fa-volleyball <%= if params[:category] == "Culture" || params[:category] == "Voyage" || params[:category] == "Autres" then 'grey-color' else 'sport-color' end %>" data-category-target="sport"></i>
        <% end %>
      </div>
      <div data-action="click->category#choose_culture">
        <%= link_to events_path(date: @date, category: (params[:category] == "Culture" ? nil : "Culture")) do %>
          <i class="align-middle fa-solid <%= if params[:category] == "Culture" then 'fa-2x' else 'fa-xl' end %> fa-book <%= if params[:category] == "Sport" || params[:category] == "Voyage" || params[:category] == "Autres" then 'grey-color' else 'culture-color' end %>" data-category-target="culture"></i>
        <% end %>
      </div>
      <div data-action="click->category#choose_voyage">
        <%= link_to events_path(date: @date, category: (params[:category] == "Voyage" ? nil : "Voyage")) do %>
          <i class="align-middle fa-solid <%= if params[:category] == "Voyage" then 'fa-2x' else 'fa-xl' end %> fa-plane-departure <%= if params[:category] == "Sport" || params[:category] == "Culture" || params[:category] == "Autres" then 'grey-color' else 'voyage-color' end %>" data-category-target="voyage"></i>
        <% end %>
      </div>
      <div data-action="click->category#choose_autres">
        <%= link_to events_path(date: @date, category: (params[:category] == "Autres" ? nil : "Autres")) do %>
          <i class="align-middle fa-solid <%= if params[:category] == "Autres" then 'fa-2x' else 'fa-xl' end %> fa-star-of-life <%= if params[:category] == "Sport" || params[:category] == "Culture" || params[:category] == "Voyage" then 'grey-color' else 'autres-color' end %>" data-category-target="autres"></i>
        <% end %>
      </div>
    </div>
  </div>

  <% if @events.length > 0 %>
    <% date = @events.first.starts_at.strftime("%d") %>
    <div class="border1 ps-3 ms-1 border-grey">
      <% @events.each do |event| %>
        <% if event.starts_at != nil && @date.strftime("%B") == event.starts_at.strftime("%B")  %>
          <ul>
            <div <%= 'data-controller=scroll-on-connect' if @next_event == event %>>
                <%= link_to event_path(event) do %>
                  <div class="event-planning-container">
                    <% if event.starts_at.strftime("%d") != date %>
                      <% date = event.starts_at.strftime("%d") %>
                      <div class='event-day'>
                        <div class="bullet">●</div><li><%= l((event.starts_at), format: ("%a")).capitalize %> <%= event.starts_at.day %></li>
                      </div>
                    <% elsif event == @events.first %>
                      <div class='event-day'>
                        <div class="bullet">●</div><li><%= l((event.starts_at), format: ("%a")).capitalize %> <%= event.starts_at.day %></li>
                      </div>
                    <% end %>
                    <div></div>
                    <div class='event-info-wrapper <%=event.category%>'>
                      <div class='event-info d-flex' >
                        <div class='overflow-info'>
                          <strong><%= event.title %></strong>
                          <div>
                            <small>
                              <span><%= truncate(event.venue, length: 25) %></span> - <span><%= l((event.starts_at), format: ("%k:%M")) %></span>
                            </small>
                          </div>
                        </div>
                        <div class='icone-doc'><%= image_tag('componentssvg/icone-doc.svg') %></div>
                      </div>
                    </div>
                  </div>
                <% end %>
            </div>
          </ul>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/events/new.html.erb
<div class="container3 flex-grow-1">
  <div data-controller="loader">
    <%# <div class="container mb-5"> %>
        <%= link_to :back, class:'btn-back' do %>
          <i class="fa-solid fa-angle-left"></i>
        <% end %>
        <div class="form-container mt-1">
          <h3 class='mt-3 mb-4'>Ajouter un Document</h3>
          <%= simple_form_for(@event) do |f| %>
            <%= f.input :document, as: :file %>
            <%= f.submit 'Ajouter', class: 'btn-add-event my-5', data: {action: "click->loader#display"} %>
          <% end %>
        </div>
    <%# </div> %>

    <div class="transparent d-flex align-items-center justify-content-center d-none" data-loader-target="ploader">
      <div class="loader"></div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container show flex-grow-1 margin-bottom-80">

  <div class='<%= (@event.title.length >= 20) ? 'defiler' : 'regular-title'  %>'>
    <div><%= @event.title %></div>
  </div>

  <div class="event-date-cont">
    <li class='date-cont'><%= l((@event.starts_at), format: ("%d %b"))%></li>
    <li class='date-cont'><%= l((@event.starts_at), format: ("%k:%M"))%></li>
  </div>
  <div class="event-info-show">

    <li><strong><%= @event.venue %></strong></li>
    <li><%= @event.address %></li>
  </div>


  <div style="width: 100%; height: 300px; border-radius: 30px; "
  data-controller="map"
  data-map-marker-value="<%= @marker.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
  class="my-3"></div>

  <!-- Button trigger modal -->
  <button type="button" class="btn-see-pdf" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    Voir PDF
  </button>

  <!-- Modal -->
  <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-fullscreen-sm-down">
      <div class="modal-content">
        <div class="modal-body" style>
          <% if @event.document.key != nil %>
            <embed src="<%= cl_image_path @event.document.key%>" type="" height="700" width="365">
          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn-see-pdf" data-bs-dismiss="modal">Fermer</button>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="<%= meta_description %>">
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag "icons/favicon-32x32.png" %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <div class="wrapper d-flex flex-column">
      <%= yield %>
      <% if current_page?(dashboard_path) || current_page?(notifications_path) || current_page?(new_event_path) || current_page?(events_path) || current_page?(edit_user_registration_path) || (params[:controller] == 'events' && params[:action] == 'show')%>
        <%= render 'shared/bottom' %>
      <% end %>
    </div>
  </body>
</html>

app/views/notifications/_notification.html.erb
<div class='notification-card'>
  <div>
    <%= notification.content %>
  </div>
  <div>
    <%= link_to read_notification_path(notification), data:{turbo_method: :patch} do %>
    <i class="fa-solid fa-xmark"></i>
    <% end %>
  </div>
</div>

app/views/notifications/index.html.erb
<div class="container my-5">

  <h2 class="info-title">Toutes vos notifications</h2>

  <ul>
    <% @notifications.each do |notif| %>
      <div class="notification-card-index">
        <div class="notification-head">
          <h3> <%= notif.title %> </h3>
          <p> <small> Il y a <%=((Time.current - notif.created_at) / 60).round(0) %> minutes </small></p>
        </div>
        <p> <small><strong><%= notif.content %></strong></small></p>
      </div>
    <% end %>
  </ul>
</div>

app/views/pages/home.html.erb
<div class="container">
  <div class="home-text">
      <img class="home-pic" src="https://cdn-icons-png.flaticon.com/512/432/432312.png">
      <div>
        <h1>Tous vos billets au bon endroit et au bon moment</h1>
        <p>Chargez tous vos billets pour vos prochains évènements et ils apparaitrons automatiquement lorsque vous en aurez besoin</p>
      </div>
      <%= link_to "S'inscrire", new_user_registration_path, class: "btn-sign-up" %>
      <%= link_to "Se connecter", new_user_session_path, class: "btn-sign-in" %>
  </div>
</div>

app/views/shared/_bottom.html.erb
<div class="container cont-icons">
  <div class="bottom-icons">
    <%  unless current_page?(dashboard_path) %>
      <%= link_to dashboard_path, class: "fa-solid" do %>
        <%= image_tag('componentssvg/House.svg') %>
      <% end %>
    <% else %>
      <%= link_to dashboard_path, class: "fa-solid" do %>
        <%= image_tag('componentssvg/Houses.svg') %>
      <% end %>
    <% end %>
    <%  unless current_page?(events_path) %>
      <%= link_to events_path, class: "fa-solid" do %>
      <%= image_tag('componentssvg/calendar.svg') %>
    <% end %>
    <% else %>
      <%= link_to events_path, class: "fa-solid" do %>
        <%= image_tag('componentssvg/calendars.svg') %>
      <% end %>
    <% end %>

    <%= link_to new_event_path, class: "fa-solid bottom-btn" do %>
      <%= image_tag('componentssvg/btn-add.svg') %>
    <% end %>

    <%  unless current_page?(edit_user_registration_path) %>
      <%= link_to edit_user_registration_path, class: "fa-solid" do %>
      <%= image_tag('componentssvg/account.svg') %>
    <% end %>
    <% else %>
      <%= link_to edit_user_registration_path, class: "fa-solid" do %>
        <%= image_tag('componentssvg/accounts.svg') %>
      <% end %>
    <% end %>

    <%= link_to "", destroy_user_session_path, data: {turbo_method: :delete}, class: "fa-solid fa-arrow-right-from-bracket fa-lg "  %>
    <%=  %>
  </div>
</div>

  <%#= embedded_svg('Rectangle.svg') %>
    <%# <%= link_to embedded_svg('House.svg'), dashboard_path, class:"fa-solid" %>
    <%# <%= link_to embedded_svg('calendar.svg'), events_path, class:"fa-solid" %>
    <%#= link_to embedded_svg('btn-add.svg'), new_event_path, class:"fa-solid" %>
    <%# <%= link_to embedded_svg('account.svg'), edit_user_registration_path, class:"fa-solid" %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar">
    <%= link_to dashboard_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>
    <h2>Smarty</h2>
</div>



<%# ancien navbar  %>
  <%# <button></span>
    <ul class="navbar-nav me-auto">
      <li class="nav-item dropdown">
        <%= image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <%# <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
          <%# <%= link_to "All Events", events_path, class: "dropdown-item" %>
          <%# <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
        <%# </div> %>
      <%# </li>
    </ul>
  </button> %>